name: clean_code
description: clean architecture code generation tool for flutter and dart
version: 1.0.0
homepage: https://www.github.com/lordvidex/clean_code

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  yaml: ^3.1.0
